### ISSUE TITLE
HOW TO decode ABI

### ISSUE THREAD

**Issue by diego-G** [jacogr/ethabi-js#11]
@jacogr I would like to ask you some examples of how to use your module. I need to decode an encoded input of an internal tx.

**Comment by jacogr** [comment]
This repo (and the associated ethapi-js) has been rolled into Parity itself. 

https://github.com/ethcore/parity/tree/master/js

To decode method data, I would suggest looking at https://github.com/ethcore/parity/blob/master/js/src/api/util/decode.js
- `decodeCallData` - strips data as part of transaction in the signature & data parts
- `decodeMethodInput` - provided a method ABI and data (from the call above), decode it into the inputs

**Comment by diego-G** [comment]
Thanks for you response!

My problem is that I'm using web3 in an NodeJS app. I guess I need to do something similar that I've done to use the module trace not present in. I've extended the web3 module with the method trace_transaction or trace_filter by example. You think I have to do the same here?

I don't see the API to use its methods.

---

De: Jaco Greeff notifications@github.com
Enviado: jueves, 20 de octubre de 2016 05:49 p. m.
Para: jacogr/ethabi-js
Cc: diego-G; Author
Asunto: Re: [jacogr/ethabi-js] HOW TO decode ABI (#11)

This repo (and the associated ethapi-js) has been rolled into Parity itself.

https://github.com/ethcore/parity/tree/master/js

[https://avatars0.githubusercontent.com/u/14176906?v=3&s=400]https://github.com/ethcore/parity/tree/master/js

ethcore/parityhttps://github.com/ethcore/parity/tree/master/js
github.com
parity - Fast, light, robust Ethereum implementation

To decode method data, I would suggest looking at https://github.com/ethcore/parity/blob/master/js/src/api/util/decode.js

[https://avatars0.githubusercontent.com/u/14176906?v=3&s=400]https://github.com/ethcore/parity/blob/master/js/src/api/util/decode.js

ethcore/parityhttps://github.com/ethcore/parity/blob/master/js/src/api/util/decode.js
github.com
parity - Fast, light, robust Ethereum implementation
-   decodeCallData - strips data as part of transaction in the signature & data parts
-   decodeMethodInput - provided a method ABI and data (from the call above), decode it into the inputs

##

**Comment by jacogr** [comment]
Ok, honestly not a web3 expert myself - last time I used it was around Feb before the work on the replacement API started. However, knowing how the extends work, a similar approach would probably work. However for decoding, as I recall the ABI stuff is baked into web3, I just don't know how it fits exactly.

Sadly, we are not yet publishing the Parity.js stuff to npm yet - for 1.4 (due in the next couple of days), we have been focussing on getting the UI ready. For 1.5 we will push the API/ABI to npm. Obviously in 1.4 we do allow people to write dapps with our APIs, however it doesn't quite meet the needs of all uses with "just pull in the module".

I wish I could be much more help at exactly this point in time :(

**Comment by diego-G** [comment]
Is it really impossible to use your library ethabi-js to decode an ABI call input? I would like to do what it is explained here https://github.com/ethereumjs/ethereumjs-abi#encoding-and-decoding-aided-by-the-json-abi-definition

I cannot use their module neither cause there is a problem with the installation of "sha3" dependencie module...

[https://avatars1.githubusercontent.com/u/16297473?v=3&s=400]https://github.com/ethereumjs/ethereumjs-abi

GitHub - ethereumjs/ethereumjs-abi: Decoder and encoder ...https://github.com/ethereumjs/ethereumjs-abi
github.com
Module implementing the Ethereum ABI in Javascript. Can be used with RPC libraries for communication or with ethereumjs-vm to implement a fully fledged simulator ...

---

De: Jaco Greeff notifications@github.com
Enviado: jueves, 20 de octubre de 2016 10:02 p. m.
Para: jacogr/ethabi-js
Cc: diego-G; Author
Asunto: Re: [jacogr/ethabi-js] HOW TO decode ABI (#11)

Ok, honestly not a web3 expert myself - last time I used it was around Feb before the work on the replacement API started. However, knowing how the extends work, a similar approach would probably work. However for decoding, as I recall the ABI stuff is baked into web3, I just don't know how it fits exactly.

Sadly, we are not yet publishing the Parity.js stuff to npm yet - for 1.4 (due in the next couple of days), we have been focussing on getting the UI ready. For 1.5 we will push the API/ABI to npm. Obviously in 1.4 we do allow people to write dapps with our APIs, however it doesn't quite meet the needs of all uses with "just pull in the module".

I wish I could be much more help at exactly this point in time :(

##
